//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HISTORY_IMAGES
    {
        public long HISTORYIMAGES_ID { get; set; }
        public Nullable<System.DateTime> HISTORYIMAGES_TIMESTART { get; set; }
        public Nullable<System.DateTime> HISTORYIMAGES_TIMEEND { get; set; }
        public string HISTORYIMAGES_URL { get; set; }
        public long USER_ID { get; set; }
        public long CAMERA_ID { get; set; }
        public Nullable<short> FUNCTION_ID { get; set; }
        public string HISTORYIMAGES_INFO { get; set; }
        public Nullable<long> HISTORY_VIDEO_ID { get; set; }
    
        public virtual TBL_CAMERA TBL_CAMERA { get; set; }
        public virtual TBL_FUNCTION TBL_FUNCTION { get; set; }
        public virtual TBL_USER TBL_USER { get; set; }
        public virtual TBL_HISTORY_VIDEO TBL_HISTORY_VIDEO { get; set; }
    }
}
