//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CAMERA_FUNCTION
    {
        public Nullable<short> FUNCTION_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<long> CAMERA_ID { get; set; }
        public string POLYGON { get; set; }
        public Nullable<short> X_ROTATION { get; set; }
        public Nullable<short> Y_ROTATION { get; set; }
        public Nullable<short> Z_ROTATION { get; set; }
        public Nullable<short> STRETCH { get; set; }
        public Nullable<short> DISTANCE { get; set; }
        public long CAMERA_FUNTION_ID { get; set; }
        public string URL_IMAGE { get; set; }
        public Nullable<short> IMAGE_STATUS { get; set; }
    
        public virtual TBL_CAMERA TBL_CAMERA { get; set; }
        public virtual TBL_FUNCTION TBL_FUNCTION { get; set; }
        public virtual TBL_USER TBL_USER { get; set; }
    }
}
