//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_ROLE
    {
        public long USER_ID { get; set; }
        public short ROLE_ID { get; set; }
        public string USER_ROLE_DESCRIPTION { get; set; }
        public string ROLE_NAME { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<long> AGENCY_ID { get; set; }
    
        public virtual TBL_ROLE TBL_ROLE { get; set; }
        public virtual TBL_USER TBL_USER { get; set; }
    }
}
