//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PROFILE_USER
    {
        public long PROFILE_USER_ID { get; set; }
        public string FULL_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string DISTRICT { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public Nullable<short> SEX { get; set; }
        public string PHONE { get; set; }
        public string MOBILE { get; set; }
        public string ID_NUMBER { get; set; }
        public long USER_ID { get; set; }
    
        public virtual TBL_USER TBL_USER { get; set; }
    }
}
