//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CAMERA
    {
        public TBL_CAMERA()
        {
            this.TBL_CAMERA_STATUS = new HashSet<TBL_CAMERA_STATUS>();
            this.TBL_HISTORY_IMAGES = new HashSet<TBL_HISTORY_IMAGES>();
            this.TBL_HISTORY_VIDEO = new HashSet<TBL_HISTORY_VIDEO>();
            this.TBL_CAMERA_FUNCTION = new HashSet<TBL_CAMERA_FUNCTION>();
        }
    
        public long CAMERA_ID { get; set; }
        public string CAMERA_NAME { get; set; }
        public string CAMERA_NUMBER { get; set; }
        public string CAMERA_URL { get; set; }
        public string CAMERA_IP { get; set; }
        public long USER_ID { get; set; }
        public string CAMERA_URL_STREAM { get; set; }
        public Nullable<short> SNAPSHOT_STATUS { get; set; }
        public string IMAGE_URL { get; set; }
    
        public virtual ICollection<TBL_CAMERA_STATUS> TBL_CAMERA_STATUS { get; set; }
        public virtual ICollection<TBL_HISTORY_IMAGES> TBL_HISTORY_IMAGES { get; set; }
        public virtual ICollection<TBL_HISTORY_VIDEO> TBL_HISTORY_VIDEO { get; set; }
        public virtual TBL_USER TBL_USER { get; set; }
        public virtual ICollection<TBL_CAMERA_FUNCTION> TBL_CAMERA_FUNCTION { get; set; }
    }
}
