//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TOKEN
    {
        public long TOKEN_ID { get; set; }
        public long USER_ID { get; set; }
        public string AUTH_TOKEN { get; set; }
        public Nullable<System.DateTime> ISSUED_ON { get; set; }
        public Nullable<System.DateTime> EXPIRES_ON { get; set; }
    
        public virtual TBL_USER TBL_USER { get; set; }
    }
}
