//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CAMERA_STATUS
    {
        public Nullable<short> CAMERA_STATUS { get; set; }
        public string CAMERA_STATUS_DESCRIPTION { get; set; }
        public long CAMERA_ID { get; set; }
        public short FUNCTION_ID { get; set; }
        public long CAMERA_STATUS_ID { get; set; }
        public string CAMERA_STATUS_TIME_START { get; set; }
        public string CAMERA_STATUS_TIME_END { get; set; }
        public Nullable<short> FUNCTION_REGIGES { get; set; }
    
        public virtual TBL_CAMERA TBL_CAMERA { get; set; }
        public virtual TBL_FUNCTION TBL_FUNCTION { get; set; }
    }
}
