//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER
    {
        public TBL_USER()
        {
            this.TBL_CAMERA = new HashSet<TBL_CAMERA>();
            this.TBL_CAMERA_FUNCTION = new HashSet<TBL_CAMERA_FUNCTION>();
            this.TBL_HISTORY_IMAGES = new HashSet<TBL_HISTORY_IMAGES>();
            this.TBL_HISTORY_VIDEO = new HashSet<TBL_HISTORY_VIDEO>();
            this.TBL_PROFILE_USER = new HashSet<TBL_PROFILE_USER>();
            this.TBL_TOKEN = new HashSet<TBL_TOKEN>();
            this.TLB_USER_HISTORY = new HashSet<TLB_USER_HISTORY>();
            this.TBL_USER_ROLE = new HashSet<TBL_USER_ROLE>();
            this.TBL_FEEDBACK = new HashSet<TBL_FEEDBACK>();
        }
    
        public long USER_ID { get; set; }
        public string NAME { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORDS { get; set; }
        public string EMAIL { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<short> USER_STATUS { get; set; }
        public short USER_ACTIVE { get; set; }
        public Nullable<long> AGENCY_ID { get; set; }
        public string TAX_CODE { get; set; }
        public Nullable<long> PHONE { get; set; }
        public string REPRESENTATIVE { get; set; }
        public string ADDRESS { get; set; }
        public string IMAGE_URL { get; set; }
        public string CONFIGPASSWORDS { get; set; }
        public Nullable<short> REVIEW { get; set; }
        public string TOKEN_KEY { get; set; }
    
        public virtual ICollection<TBL_CAMERA> TBL_CAMERA { get; set; }
        public virtual ICollection<TBL_CAMERA_FUNCTION> TBL_CAMERA_FUNCTION { get; set; }
        public virtual ICollection<TBL_HISTORY_IMAGES> TBL_HISTORY_IMAGES { get; set; }
        public virtual ICollection<TBL_HISTORY_VIDEO> TBL_HISTORY_VIDEO { get; set; }
        public virtual ICollection<TBL_PROFILE_USER> TBL_PROFILE_USER { get; set; }
        public virtual ICollection<TBL_TOKEN> TBL_TOKEN { get; set; }
        public virtual ICollection<TLB_USER_HISTORY> TLB_USER_HISTORY { get; set; }
        public virtual ICollection<TBL_USER_ROLE> TBL_USER_ROLE { get; set; }
        public virtual ICollection<TBL_FEEDBACK> TBL_FEEDBACK { get; set; }
    }
}
