//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FEEDBACK
    {
        public long FEEDBACK_ID { get; set; }
        public long USER_ID { get; set; }
        public string FEEDBACK_CONTENT { get; set; }
        public System.DateTime FEEDBACK_TIME { get; set; }
        public string TITLE { get; set; }
    
        public virtual TBL_USER TBL_USER { get; set; }
    }
}
