//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ROLE
    {
        public TBL_ROLE()
        {
            this.TBL_PERMISSTION = new HashSet<TBL_PERMISSTION>();
            this.TBL_USER_ROLE = new HashSet<TBL_USER_ROLE>();
        }
    
        public short ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public Nullable<short> ROLE_ORD { get; set; }
        public string ROLE_DESCRIPTION { get; set; }
    
        public virtual ICollection<TBL_PERMISSTION> TBL_PERMISSTION { get; set; }
        public virtual ICollection<TBL_USER_ROLE> TBL_USER_ROLE { get; set; }
    }
}
