//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PERMISSTION
    {
        public short PERMISSTION_ID { get; set; }
        public string PERMISSTION_NAME { get; set; }
        public Nullable<short> PERMISSTIONS { get; set; }
        public short ROLE_ID { get; set; }
        public string PERMISSTION_DESCRIPTION { get; set; }
    
        public virtual TBL_ROLE TBL_ROLE { get; set; }
    }
}
