//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UPDATE_STATUS
    {
        public long UPDATE_STATUS_ID { get; set; }
        public Nullable<short> STATUS_UPDATE { get; set; }
    }
}
