//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FUNCTION
    {
        public TBL_FUNCTION()
        {
            this.TBL_CAMERA_FUNCTION = new HashSet<TBL_CAMERA_FUNCTION>();
            this.TBL_CAMERA_STATUS = new HashSet<TBL_CAMERA_STATUS>();
            this.TBL_HISTORY_IMAGES = new HashSet<TBL_HISTORY_IMAGES>();
        }
    
        public short FUNCTION_ID { get; set; }
        public string FUNCTION_NAME { get; set; }
        public string FUNCTION_DESCRIPTION { get; set; }
        public string FUNCTION_IMAGE { get; set; }
        public Nullable<short> PROCESS { get; set; }
    
        public virtual ICollection<TBL_CAMERA_FUNCTION> TBL_CAMERA_FUNCTION { get; set; }
        public virtual ICollection<TBL_CAMERA_STATUS> TBL_CAMERA_STATUS { get; set; }
        public virtual ICollection<TBL_HISTORY_IMAGES> TBL_HISTORY_IMAGES { get; set; }
    }
}
