//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLB_USER_HISTORY
    {
        public long USER_HISTORY_ID { get; set; }
        public Nullable<System.DateTime> USER_HISTORY_TIMESTART { get; set; }
        public Nullable<System.DateTime> USER_HISTORY_TIMEEND { get; set; }
        public string USER_HISTORY_COMMAND { get; set; }
        public long USER_ID { get; set; }
    
        public virtual TBL_USER TBL_USER { get; set; }
    }
}
